baseURL = "https://lovekorea.me/"
languageCode = "en-us"
title = "Love Korea"
theme = "PaperMod"
defaultContentLanguage = "en"
enableRobotsTXT = true
paginate = 10

[params]
  description = "A blog for K-culture lovers. Discover Korean food, beauty, drama, and more!"
  keywords = ["Korean culture", "Korean food", "K-beauty", "K-dramas", "Learn Korean", "K-pop", "Visit Korea"]

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3