baseURL = "https://lovekorea.me/"
languageCode = "en"
title = "LoveKorea Blog"
theme = "PaperMod"
enableRobotsTXT = true

defaultContentLanguage = "en"

[pagination]
  pagerSize = 10

[params]
  author = "LoveKorea"
  description = "A blog for people around the world who love Korean culture"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowToc = true
  defaultTheme = "auto"
  disableThemeToggle = false
  DateFormat = "2006-01-02"
  ShowCodeCopyButtons  = true
  ShowCover  = true
  ShowSummaryCover  = true
  disableSpecial1stPost = true
  TocOpen = true

  [params.homeInfoParams]
    Title = "Welcome to LoveKorea"
 

  [params.assets]
    disableFingerprinting = false
    css = ["css/custom.css"]

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

