baseURL = "https://lovekorea.me/"
languageCode = "ko-kr"
title = "Love Korea"
theme = "PaperMod"  # 테마 이름에 맞게 수정
paginate = 10

[menu]

[[menu.main]]
  name = "K-FOOD"
  url = "/k-food/"
  weight = 1

[[menu.main]]
  name = "K-Beauty"
  url = "/k-beauty/"
  weight = 2

[[menu.main]]
  name = "K-Music"
  url = "/k-music/"
  weight = 3

[[menu.main]]
  name = "K-Drama"
  url = "/k-drama/"
  weight = 4
