baseURL = "https://lovekorea.me/"
languageCode = "en"
title = "LoveKorea Blog"
theme = "PaperMod"
enableRobotsTXT = true

defaultContentLanguage = "en"

[pagination]
  pagerSize = 10

[params]
  ShowPostIcons = true
  ShowBreadCrumbs = true
  ShowReadingTime = true
  ShowShareButtons = true
  ShowCodeCopyButtons = true
  defaultTheme = "auto"
  heroImage = "/images/hero.jpg"

  author = "LoveKorea"
  description = "A blog for people around the world who love Korean culture"
  ShowPostNavLinks = true
  ShowToc = true
  disableThemeToggle = false
  DateFormat = "2006-01-02"
  
  [params.homeInfoParams]
    Title = "Welcome to LoveKorea"
    Content = "Discover food, fashion, K-pop, drama, and everything about Korean culture!"

  [params.assets]
    disableFingerprinting = false

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4
